contact_links:
    - name: Get support
      url: https://contao.org/en/support.html
      about: If you need help using Contao or the Contao Manager, pick a support option on contao.org

blank_issues_enabled: false
