imports:
    - { resource: config.yaml }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: file

        file:
            type: error_log
