imports:
    - { resource: config.yaml }

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/api.log"
            level: INFO
            channels: ['!event', '!security', '!request']
            max_files: 10
