imports:
    - { resource: services.yaml }

# The secret is only required to sign fragment URLs which is not used
framework:
    secret: ''
    default_locale: en
    router:
        resource: kernel::loadRoutes
        type: service

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        contao_manager_user_provider:
            id: Contao\ManagerApi\Security\UserProvider

    firewalls:
        api:
            stateless: true
            provider: contao_manager_user_provider
            custom_authenticators:
                - Contao\ManagerApi\Security\LoginAuthenticator
                - Contao\ManagerApi\Security\PasswordlessAuthenticator
                - Contao\ManagerApi\Security\InvitationAuthenticator
                - Contao\ManagerApi\Security\JwtAuthenticator
                - Contao\ManagerApi\Security\TokenAuthenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_INSTALL
        ROLE_INSTALL: ROLE_UPDATE
        ROLE_UPDATE: ROLE_READ
        ROLE_READ: ROLE_USER

    access_control:
        - { path: ^/api/session$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
