cyon.ch:
    name: cyon GmbH
    website: www.cyon.ch
    last_update: 2017-05-31
    issues: []
    php:
        /opt/alt/php{major}{minor}/usr/bin/php: []

goserver.host:
    name: webgo GmbH
    website: www.webgo.de
    last_update: 2017-06-19
    issues: []
    php:
        /usr/bin/php{major}{minor}: []

hosteurope.de:
    name: Host Europe GmbH
    website: www.hosteurope.de
    last_update: 2017-06-27
    issues: []
    php:
        /usr/bin/php{major}.{minor}: ['-d', 'memory_limit=2048M', '-d', 'suhosin.executor.include.whitelist="phar://,http://,https://"']
        /usr/bin/php: ['-d', 'memory_limit=2048M', '-d', 'suhosin.executor.include.whitelist="phar://,http://,https://"']

inetrobots.com:
    name: Hostingwerk (Feyer Media GmbH & Co. KG)
    website: www.hostingwerk.de
    last_update: 2017-06-13
    issues: []
    php:
        /usr/bin/php-{major}.{minor}: []

ispgateway.de:
    name: domainfactory GmbH
    website: www.df.eu
    last_update: 2017-06-20
    issues: [memory]
    php:
        /usr/local/bin/php{major}-{major}{minor}LATEST-CLI: []

kasserver.com:
    name: ALL-INKL.COM - Neue Medien Münnich
    website: www.all-inkl.com
    last_update: 2017-06-17
    issues: []
    php:
        /usr/bin/php{major}{minor}: []
        /usr/bin/php: []

kundenserver.de:
    name: 1&1 Internet SE
    website: www.1und1.de
    last_update: 2017-06-20
    issues: [cputime, memory]
    php:
        /usr/bin/php{major}.{minor}-cli: ['-d', 'memory_limit=-1']
        /usr/bin/php{major}.{minor}: []
        /usr/lib/cgi-bin/php{major}.{minor}: []

mittwald.de:
    name: Mittwald CM Service GmbH & Co. KG
    website: www.mittwald.de
    last_update: 2017-09-17
    issues: []
    php:
        /usr/local/bin/php_cli: []

netcup.net:
    name: netcup GmbH
    website: www.netcup.de
    last_update: 2017-06-27
    issues: []
    php:
        /usr/local/php56/bin/php: ['-d', 'date.timezone=UTC']
        /usr/local/php{major}{minor}/bin/php: []

rzone.de:
    name: Strato AG
    website: www.strato.de
    last_update: 2017-05-31
    issues: [intl, memory]
    php:
        /usr/bin/php{major}.{minor}: []

serverdomain.org:
    name: WebhostOne GmbH
    website: www.webhostone.de
    last_update: 2017-06-18
    issues: []
    php:
        /usr/bin/php{major}{minor}: []
        /usr/bin/php: []

sui-inter.net:
    name: Metanet AG
    website: www.metanet.ch
    last_update: 2017-05-31
    issues: []
    php:
        /opt/php{major}{minor}/bin/php: []
        /usr/bin/php: []

tophost.ch:
    name: Novatrend Services GmbH
    website: www.novatrend.ch
    last_update: 2017-05-31
    issues: [cputime]
    php:
        /usr/local/bin/php: []

uberspace.de:
    name: Uberspace
    website: www.uberspace.de
    last_update: 2017-07-12
    issues: []

vhost.io:
    name: Hostingwerk (Feyer Media GmbH & Co. KG)
    website: www.hostingwerk.de
    last_update: 2017-06-13
    issues: []
    php:
        /usr/bin/php-{major}.{minor}: []

your-server.de:
    name: Hetzner Online GmbH
    website: www.hetzner.de
    last_update: 2017-06-26
    issues: []
    php:
        /usr/bin/php{major}{minor}: []
        /usr/bin/php: []
