name: CI

on:
    push: ~
    pull_request: ~

permissions: read-all

defaults:
    run:
        # Simulate an interactive terminal with color support
        shell: script -q -e -c "export TERM=xterm; bash {0}"

jobs:
    rector:
        name: Rector
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install Contao Manager
              uses: ramsey/composer-install@v3

            - name: Install Rector
              uses: ramsey/composer-install@v3
              with:
                  working-directory: vendor-bin/rector

            - name: Run Rector
              run: vendor-bin/rector/vendor/bin/rector --dry-run --no-progress-bar

    ecs:
        name: ECS
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install Contao Manager
              uses: ramsey/composer-install@v3

            - name: Install ECS
              uses: ramsey/composer-install@v3
              with:
                  working-directory: vendor-bin/ecs

            - name: Run ECS
              run: vendor-bin/ecs/vendor/bin/ecs check --no-progress-bar

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install Contao Manager
              uses: ramsey/composer-install@v3

            - name: Install PHPStan
              uses: ramsey/composer-install@v3
              with:
                  working-directory: vendor-bin/phpstan

            - name: Run PHPStan
              run: vendor-bin/phpstan/vendor/bin/phpstan analyse --no-progress

    depcheck:
        name: Depcheck
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  show-progress: false

            - name: Install Contao Manager
              uses: ramsey/composer-install@v3

            - name: Check for unknown symbols
              run: vendor/bin/composer-dependency-analyser --config=depcheck.php

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2, 8.3]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install Contao Manager
              uses: ramsey/composer-install@v3

            - name: Run the unit tests
              run: vendor/bin/phpunit

    nightly:
        name: PHP 8.4
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install Contao Manager
              uses: ramsey/composer-install@v3
              with:
                  composer-options: --ignore-platform-req=php+
